[package]
edition = "2024"
name = "agentx"
description = "An Agent Studio"
publish = false
version = "0.5.0"

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui-component.workspace = true
rust-embed = { version = "8", features = ["interpolate-folder-path"] }
serde = "1"
serde_json = "1"
rand = "0.8"
autocorrect = "2.14.2"
chrono = { version = "0.4", features = ["serde"] }
tree-sitter-navi = "0.2.2"
smol.workspace = true
color-lsp = "0.2.0"
lsp-types.workspace = true
reqwest_client = { path = "../../crates/reqwest_client" }

tracing.workspace = true
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
agent-client-protocol = "0.8.0"
log.workspace = true
tokio-util = { version = "0.7.17", features = ["compat"] }
tokio = { version = "1.48.0", features = ["rt", "rt-multi-thread", "process", "fs", "io-util"] }
async-trait = "0.1.89"
rfd = "0.15"
uuid = { version = "1.11", features = ["v4"] }
rust-i18n.workspace = true
regex = "1"
base64 = "0.22"
which = "7.0"


[lints]
workspace = true
